# Site settings
title: mikeborsare.com
email: mborsare@gmail.com?subject=Hi%20Mike
description: "I’m Mike – a MassArt educated graphic designer living and working in Boston MA. It’s cold here (I’m from Tennessee by way of Alabama)."
baseurl: ""
url: "http://mikeborsare.com"

# Build settings
markdown: kramdown
permalink: /work/:title

sass_dir: _sass
